version: 0.0.1

debug: false

# reward.amount will only accept whole numbers
reward:
  amount: 100
# reward-timer.duration change requires restart
# duration in seconds
reward-timer:
  duration: 60

# request.lifespan change requires restart
# lifespan of a buddy request in seconds
request:
  lifespan: 15