name: BuddyBonus
version: '${project.version}'
main: com.playtheatria.buddybonus.BuddyBonus
api-version: '1.20'
depend: [Essentials]
commands:
  buddy:
    description: for the buddies system
    usage: |
      /<command> add <name>
      /<command> remove
      /<command> accept
      /<command> notify
  abuddy:
    description: admin commands
    usage: |
      /<command> list
      /<command> disband <name>
      /<command> reload